name: Build and Publish Jar

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew clean build

      - name: Publish Package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}